### ISSUE TITLE
Fitting results

### ISSUE THREAD

**Issue by Jackson898** [zmanaa/SINDY-DMD-Quadrotor#1]
Hello, I tried to run your code and found that the final fitting results are not the same. Is there a problem in any aspect? Thanks for your answer!

**Comment by zmanaa** [comment]
Dear Jakson, 

Thanks for your input. This was only a self documentation for my workflow and forget to update it with final edits until now.
So, kindly check it now, the updated version should work smoothly with you. Check the training.ipynb file under SINDY TRAINING directory to make sure you get the model correctly.

If it worked with you please let me know to close the issue.

Regards.

**Comment by Jackson898** [comment]
Ok, I'll give it a try and let you know in time. Thank you for your work!

**Comment by Jackson898** [comment]
Dear Zmanaa,
       I've tried running the project and got the right fit. You can close the issue. Thank you for your contributions to the Sindy algorithm. Best wishes for you.
